spring:
  application:
    name: alga-foods-api

  # datasource
  datasource:
    url: jdbc:sqlserver://LUCAS-ALVES:1433;databaseName=AlgaFoods;encrypt=false
    username: usr_alga_foods
    password: algaF00ds#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  #serialization
  jackson:
    serialization:
      fail-on-empty-beans: false

  #spring security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

server:
  error:
    include-stacktrace: NEVER
